packages:
  kauf.plf10-update: !include ../../PLF10/config/kauf-plug-update.yaml
  kauf.plf12-base:   !include kauf-plf12-base.yaml

dashboard_import:
  package_import_url: github://KaufHA/PLF12/kauf-plf12.yaml
